version: '3'
services:
  caddy:
    build: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    network_mode: host
    volumes:
      - ./caddy:/caddy
      - ./.caddy:/root/.caddy
    logging:
      driver: json-file
      options:
        max-size: 5m
    env_file: .env
